-- Generado por scripts/generate-paraguay-cities-sql.mjs — 263 municipios
-- Fuente: Wikipedia (Anexo:Distritos de Paraguay). pagopar_city_code = hub PagoPar (1–15).

insert into tradexpar.paraguay_cities (name, department, pagopar_city_code, sort_order)
values
  ('Bahía Negra', 'Alto Paraguay', '11', 1),
  ('Capitán Carmelo Peralta', 'Alto Paraguay', '11', 2),
  ('Fuerte Olimpo', 'Alto Paraguay', '11', 3),
  ('Puerto Casado', 'Alto Paraguay', '11', 4),
  ('Ciudad del Este', 'Alto Paraná', '2', 5),
  ('Doctor Juan León Mallorquín', 'Alto Paraná', '2', 6),
  ('Doctor Raúl Peña', 'Alto Paraná', '2', 7),
  ('Domingo Martínez de Irala', 'Alto Paraná', '2', 8),
  ('Hernandarias', 'Alto Paraná', '2', 9),
  ('Iruña', 'Alto Paraná', '2', 10),
  ('Itakyry', 'Alto Paraná', '2', 11),
  ('Juan Emiliano O''Leary', 'Alto Paraná', '2', 12),
  ('Los Cedrales', 'Alto Paraná', '2', 13),
  ('Mbaracayú', 'Alto Paraná', '2', 14),
  ('Minga Guazú', 'Alto Paraná', '2', 15),
  ('Minga Porá', 'Alto Paraná', '2', 16),
  ('Naranjal', 'Alto Paraná', '2', 17),
  ('Ñacunday', 'Alto Paraná', '2', 18),
  ('Presidente Franco', 'Alto Paraná', '2', 19),
  ('San Alberto', 'Alto Paraná', '2', 20),
  ('San Cristóbal', 'Alto Paraná', '2', 21),
  ('Santa Fe del Paraná', 'Alto Paraná', '2', 22),
  ('Santa Rita', 'Alto Paraná', '2', 23),
  ('Santa Rosa del Monday', 'Alto Paraná', '2', 24),
  ('Tavapy', 'Alto Paraná', '2', 25),
  ('Yguazú', 'Alto Paraná', '2', 26),
  ('Bella Vista Norte', 'Amambay', '11', 27),
  ('Capitán Bado', 'Amambay', '11', 28),
  ('Cerro Corá', 'Amambay', '11', 29),
  ('Karapaí', 'Amambay', '11', 30),
  ('Pedro Juan Caballero', 'Amambay', '11', 31),
  ('Zanja Pytá', 'Amambay', '11', 32),
  ('Asunción', 'Asunción', '1', 33),
  ('Boquerón', 'Boquerón', '11', 34),
  ('Filadelfia', 'Boquerón', '11', 35),
  ('Loma Plata', 'Boquerón', '11', 36),
  ('Mariscal José Félix Estigarribia', 'Boquerón', '11', 37),
  ('Caaguazú', 'Caaguazú', '14', 38),
  ('Carayaó', 'Caaguazú', '12', 39),
  ('Coronel Oviedo', 'Caaguazú', '12', 40),
  ('Doctor Cecilio Báez', 'Caaguazú', '12', 41),
  ('Doctor Juan Eulogio Estigarribia', 'Caaguazú', '12', 42),
  ('Doctor Juan Manuel Frutos', 'Caaguazú', '12', 43),
  ('José Domingo Ocampos', 'Caaguazú', '12', 44),
  ('La Pastora', 'Caaguazú', '12', 45),
  ('Mariscal Francisco Solano López', 'Caaguazú', '12', 46),
  ('Nueva Londres', 'Caaguazú', '12', 47),
  ('Nueva Toledo', 'Caaguazú', '12', 48),
  ('Raúl Arsenio Oviedo', 'Caaguazú', '12', 49),
  ('Regimiento de Infantería Tres Corrales', 'Caaguazú', '12', 50),
  ('Repatriación', 'Caaguazú', '12', 51),
  ('San Joaquín', 'Caaguazú', '12', 52),
  ('San José de los Arroyos', 'Caaguazú', '12', 53),
  ('Santa Rosa del Mbutuy', 'Caaguazú', '12', 54),
  ('Simón Bolívar', 'Caaguazú', '12', 55),
  ('Tembiaporá', 'Caaguazú', '12', 56),
  ('Tres de Febrero', 'Caaguazú', '12', 57),
  ('Vaquería', 'Caaguazú', '12', 58),
  ('Yhú', 'Caaguazú', '12', 59),
  ('Abaí', 'Caazapá', '12', 60),
  ('Buena Vista', 'Caazapá', '12', 61),
  ('Caazapá', 'Caazapá', '12', 62),
  ('Doctor Moisés Santiago Bertoni', 'Caazapá', '12', 63),
  ('Fulgencio Yegros', 'Caazapá', '12', 64),
  ('General Higinio Morínigo', 'Caazapá', '12', 65),
  ('Maciel', 'Caazapá', '12', 66),
  ('San Juan Nepomuceno', 'Caazapá', '12', 67),
  ('Tavaí', 'Caazapá', '12', 68),
  ('Tres de Mayo', 'Caazapá', '12', 69),
  ('Yuty', 'Caazapá', '12', 70),
  ('Corpus Christi', 'Canindeyú', '2', 71),
  ('Curuguaty', 'Canindeyú', '2', 72),
  ('General Francisco Caballero Álvarez', 'Canindeyú', '2', 73),
  ('Itanará', 'Canindeyú', '2', 74),
  ('Katueté', 'Canindeyú', '2', 75),
  ('La Paloma del Espíritu Santo', 'Canindeyú', '2', 76),
  ('Laurel', 'Canindeyú', '2', 77),
  ('Maracaná', 'Canindeyú', '2', 78),
  ('Nueva Esperanza', 'Canindeyú', '2', 79),
  ('Puerto Adela', 'Canindeyú', '2', 80),
  ('Salto del Guairá', 'Canindeyú', '2', 81),
  ('Villa Ygatimí', 'Canindeyú', '2', 82),
  ('Yasy Cañy', 'Canindeyú', '2', 83),
  ('Yby Pytá', 'Canindeyú', '2', 84),
  ('Ybyrarobaná', 'Canindeyú', '2', 85),
  ('Ypejhú', 'Canindeyú', '2', 86),
  ('Areguá', 'Central', '1', 87),
  ('Arroyito', 'Central', '1', 88),
  ('Azotey', 'Central', '1', 89),
  ('Belén', 'Central', '1', 90),
  ('Capiatá', 'Central', '5', 91),
  ('Concepción', 'Central', '1', 92),
  ('Fernando de la Mora', 'Central', '7', 93),
  ('Guarambaré', 'Central', '1', 94),
  ('Horqueta', 'Central', '1', 95),
  ('Itá', 'Central', '1', 96),
  ('Itacuá', 'Central', '1', 97),
  ('Itauguá', 'Central', '15', 98),
  ('Julián Augusto Saldívar', 'Central', '1', 99),
  ('Lambaré', 'Central', '6', 100),
  ('Limpio', 'Central', '8', 101),
  ('Loreto', 'Central', '1', 102),
  ('Luque', 'Central', '4', 103),
  ('Mariano Roque Alonso', 'Central', '1', 104),
  ('Nueva Italia', 'Central', '1', 105),
  ('Ñemby', 'Central', '9', 106),
  ('Paso Barreto', 'Central', '1', 107),
  ('Paso Horqueta', 'Central', '1', 108),
  ('San Alfredo', 'Central', '1', 109),
  ('San Antonio', 'Central', '1', 110),
  ('San Carlos del Apa', 'Central', '1', 111),
  ('San Lázaro', 'Central', '1', 112),
  ('San Lorenzo', 'Central', '3', 113),
  ('Sargento José Félix López', 'Central', '1', 114),
  ('Villa Elisa', 'Central', '1', 115),
  ('Villeta', 'Central', '1', 116),
  ('Yby Yaú', 'Central', '1', 117),
  ('Ypacaraí', 'Central', '1', 118),
  ('Ypané', 'Central', '1', 119),
  ('Altos', 'Cordillera', '12', 120),
  ('Arroyos y Esteros', 'Cordillera', '12', 121),
  ('Atyrá', 'Cordillera', '12', 122),
  ('Caacupé', 'Cordillera', '12', 123),
  ('Caraguatay', 'Cordillera', '12', 124),
  ('Emboscada', 'Cordillera', '12', 125),
  ('Eusebio Ayala', 'Cordillera', '12', 126),
  ('Isla Pucú', 'Cordillera', '12', 127),
  ('Itacurubí de la Cordillera', 'Cordillera', '12', 128),
  ('Juan de Mena', 'Cordillera', '12', 129),
  ('Loma Grande', 'Cordillera', '12', 130),
  ('Mbocayaty del Yhaguy', 'Cordillera', '12', 131),
  ('Nueva Colombia', 'Cordillera', '12', 132),
  ('Piribebuy', 'Cordillera', '12', 133),
  ('Primero de Marzo', 'Cordillera', '12', 134),
  ('San Bernardino', 'Cordillera', '12', 135),
  ('San José Obrero', 'Cordillera', '12', 136),
  ('Santa Elena', 'Cordillera', '12', 137),
  ('Tobatí', 'Cordillera', '12', 138),
  ('Valenzuela', 'Cordillera', '12', 139),
  ('Borja', 'Guairá', '13', 140),
  ('Capitán Mauricio José Troche', 'Guairá', '13', 141),
  ('Coronel Martínez', 'Guairá', '13', 142),
  ('Doctor Botrell', 'Guairá', '13', 143),
  ('Félix Pérez Cardozo', 'Guairá', '13', 144),
  ('General Eugenio Alejandrino Garay', 'Guairá', '13', 145),
  ('Independencia', 'Guairá', '13', 146),
  ('Itapé', 'Guairá', '13', 147),
  ('Iturbe', 'Guairá', '13', 148),
  ('José A. Fassardi', 'Guairá', '13', 149),
  ('Mbocayaty del Guairá', 'Guairá', '13', 150),
  ('Natalicio Talavera', 'Guairá', '13', 151),
  ('Ñumí', 'Guairá', '13', 152),
  ('Paso Yobái', 'Guairá', '13', 153),
  ('San Salvador', 'Guairá', '13', 154),
  ('Tebicuary', 'Guairá', '13', 155),
  ('Villarrica', 'Guairá', '13', 156),
  ('Yataity del Guairá', 'Guairá', '13', 157),
  ('Alto Verá', 'Itapúa', '10', 158),
  ('Bella Vista', 'Itapúa', '10', 159),
  ('Cambyretá', 'Itapúa', '10', 160),
  ('Capitán Meza', 'Itapúa', '10', 161),
  ('Capitán Miranda', 'Itapúa', '10', 162),
  ('Carlos Antonio López', 'Itapúa', '10', 163),
  ('Carmen del Paraná', 'Itapúa', '10', 164),
  ('Coronel José Félix Bogado', 'Itapúa', '10', 165),
  ('Edelira', 'Itapúa', '10', 166),
  ('Encarnación', 'Itapúa', '10', 167),
  ('Fram', 'Itapúa', '10', 168),
  ('General Artigas', 'Itapúa', '10', 169),
  ('General Delgado', 'Itapúa', '10', 170),
  ('Hohenau', 'Itapúa', '10', 171),
  ('Itapúa Poty', 'Itapúa', '10', 172),
  ('Jesús de Tavarangüé', 'Itapúa', '10', 173),
  ('José Leandro Oviedo', 'Itapúa', '10', 174),
  ('La Paz', 'Itapúa', '10', 175),
  ('Mayor Julio Dionisio Otaño', 'Itapúa', '10', 176),
  ('Natalio', 'Itapúa', '10', 177),
  ('Nueva Alborada', 'Itapúa', '10', 178),
  ('Obligado', 'Itapúa', '10', 179),
  ('Pirapó', 'Itapúa', '10', 180),
  ('San Cosme y Damián', 'Itapúa', '10', 181),
  ('San Juan del Paraná', 'Itapúa', '10', 182),
  ('San Pedro del Paraná', 'Itapúa', '10', 183),
  ('San Rafael del Paraná', 'Itapúa', '10', 184),
  ('Tomás Romero Pereira', 'Itapúa', '10', 185),
  ('Trinidad', 'Itapúa', '10', 186),
  ('Yatytay', 'Itapúa', '10', 187),
  ('Ayolas', 'Misiones', '10', 188),
  ('San Ignacio Guazú', 'Misiones', '10', 189),
  ('San Juan Bautista', 'Misiones', '10', 190),
  ('San Miguel', 'Misiones', '10', 191),
  ('San Patricio', 'Misiones', '10', 192),
  ('Santa María de Fe', 'Misiones', '10', 193),
  ('Santa Rosa de Lima', 'Misiones', '10', 194),
  ('Santiago', 'Misiones', '10', 195),
  ('Villa Florida', 'Misiones', '10', 196),
  ('Yabebyry', 'Misiones', '10', 197),
  ('Alberdi', 'Ñeembucú', '10', 198),
  ('Cerrito', 'Ñeembucú', '10', 199),
  ('Desmochados', 'Ñeembucú', '10', 200),
  ('General José Eduvigis Díaz', 'Ñeembucú', '10', 201),
  ('Guazú Cuá', 'Ñeembucú', '10', 202),
  ('Humaitá', 'Ñeembucú', '10', 203),
  ('Isla Umbú', 'Ñeembucú', '10', 204),
  ('Laureles', 'Ñeembucú', '10', 205),
  ('Mayor José Martínez', 'Ñeembucú', '10', 206),
  ('Paso de Patria', 'Ñeembucú', '10', 207),
  ('Pilar', 'Ñeembucú', '10', 208),
  ('San Juan Bautista de Ñeembucú', 'Ñeembucú', '10', 209),
  ('Tacuaras', 'Ñeembucú', '10', 210),
  ('Villa Franca', 'Ñeembucú', '10', 211),
  ('Villa Oliva', 'Ñeembucú', '10', 212),
  ('Villalbín', 'Ñeembucú', '10', 213),
  ('Acahay', 'Paraguarí', '6', 214),
  ('Caapucú', 'Paraguarí', '6', 215),
  ('Carapeguá', 'Paraguarí', '6', 216),
  ('Escobar', 'Paraguarí', '6', 217),
  ('General Bernardino Caballero', 'Paraguarí', '6', 218),
  ('La Colmena', 'Paraguarí', '6', 219),
  ('María Antonia', 'Paraguarí', '6', 220),
  ('Mbuyapey', 'Paraguarí', '6', 221),
  ('Paraguarí', 'Paraguarí', '6', 222),
  ('Pirayú', 'Paraguarí', '6', 223),
  ('Quiindy', 'Paraguarí', '6', 224),
  ('Quyquyhó', 'Paraguarí', '6', 225),
  ('San Roque González de Santa Cruz', 'Paraguarí', '6', 226),
  ('Sapucai', 'Paraguarí', '6', 227),
  ('Tebicuarymí', 'Paraguarí', '6', 228),
  ('Yaguarón', 'Paraguarí', '6', 229),
  ('Ybycuí', 'Paraguarí', '6', 230),
  ('Ybytymí', 'Paraguarí', '6', 231),
  ('Antequera', 'Presidente Hayes', '1', 232),
  ('Benjamín Aceval', 'Presidente Hayes', '1', 233),
  ('Campo Aceval', 'Presidente Hayes', '1', 234),
  ('Capiibary', 'Presidente Hayes', '1', 235),
  ('Choré', 'Presidente Hayes', '1', 236),
  ('General Elizardo Aquino', 'Presidente Hayes', '1', 237),
  ('General Isidoro Resquín', 'Presidente Hayes', '1', 238),
  ('General José María Bruguez', 'Presidente Hayes', '1', 239),
  ('Guayaibí', 'Presidente Hayes', '1', 240),
  ('Itacurubí del Rosario', 'Presidente Hayes', '1', 241),
  ('José Falcón', 'Presidente Hayes', '1', 242),
  ('Liberación', 'Presidente Hayes', '1', 243),
  ('Lima', 'Presidente Hayes', '1', 244),
  ('Nanawa', 'Presidente Hayes', '1', 245),
  ('Nueva Asunción', 'Presidente Hayes', '1', 246),
  ('Nueva Germania', 'Presidente Hayes', '1', 247),
  ('Puerto Pinasco', 'Presidente Hayes', '1', 248),
  ('San Estanislao', 'Presidente Hayes', '1', 249),
  ('San José del Rosario', 'Presidente Hayes', '1', 250),
  ('San Pablo', 'Presidente Hayes', '1', 251),
  ('San Pedro de Ycuamandiyú', 'Presidente Hayes', '1', 252),
  ('San Vicente Pancholo', 'Presidente Hayes', '1', 253),
  ('Santa Rosa del Aguaray', 'Presidente Hayes', '1', 254),
  ('Tacuatí', 'Presidente Hayes', '1', 255),
  ('Teniente Esteban Martínez', 'Presidente Hayes', '1', 256),
  ('Teniente Primero Manuel Irala Fernández', 'Presidente Hayes', '1', 257),
  ('Unión', 'Presidente Hayes', '1', 258),
  ('Veinticinco de Diciembre', 'Presidente Hayes', '1', 259),
  ('Villa del Rosario', 'Presidente Hayes', '1', 260),
  ('Villa Hayes', 'Presidente Hayes', '1', 261),
  ('Yataity del Norte', 'Presidente Hayes', '1', 262),
  ('Yrybucuá', 'Presidente Hayes', '1', 263)
on conflict (name, department) do update set
  pagopar_city_code = excluded.pagopar_city_code,
  sort_order = excluded.sort_order;
